version: '3'
services:
  database:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - .:/usr/src/
      - /usr/src/node_modules
    environment:
      DATABASE_URL: 'postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public'

volumes:
  postgres:
